updated

diff --git a/build b/build
--- a/build
+++ b/build
@@ -37,12 +37,25 @@ printerror() {
 	echo -e "\e[0;31m::\e[0m $*"
 }
 
+bindmount() {
+	mount --bind $1 $2
+}
+
+unmount() {
+	while true; do
+		mountpoint -q $1 || break
+		umount $1 2>/dev/null
+	done
+}
+
 chroot_run() {
+	mountbind_cache
 	mount_pseudofs
 	cp -L /etc/resolv.conf $ROOTFSDIR/etc/
 	chroot $ROOTFSDIR $@
 	retval=$?
 	umount_pseudofs
+	umountbind_cache
 	return $retval
 }
 
@@ -55,42 +68,38 @@ mount_pseudofs() {
 }
 
 umount_pseudofs() {
-	mountpoint -q $ROOTFSDIR/run && umount -l $ROOTFSDIR/run
-	mountpoint -q $ROOTFSDIR/sys && umount -l $ROOTFSDIR/sys
-	mountpoint -q $ROOTFSDIR/proc && umount -l $ROOTFSDIR/proc
-	mountpoint -q $ROOTFSDIR/dev/pts && umount -l $ROOTFSDIR/dev/pts
-	mountpoint -q $ROOTFSDIR/dev && umount -l $ROOTFSDIR/dev
+	for d in run sys proc dev/pts dev; do
+		unmount $ROOTFSDIR/$d
+	done
 }
 
 mountbind_cache() {
 	# mount bind cachedir
 	mkdir -p $SRC_CACHE $PKG_CACHE
-	mount --bind $SRC_CACHE $ROOTFSDIR/var/cache/scratchpkg/sources
-	mount --bind $PKG_CACHE $ROOTFSDIR/var/cache/scratchpkg/packages
+	bindmount $SRC_CACHE $ROOTFSDIR/var/cache/scratchpkg/sources
+	bindmount $PKG_CACHE $ROOTFSDIR/var/cache/scratchpkg/packages
 }
 
 umountbind_cache() {
 	# umount binded cachedir
-	mountpoint -q $ROOTFSDIR/var/cache/scratchpkg/sources && umount -l $ROOTFSDIR/var/cache/scratchpkg/sources
-	mountpoint -q $ROOTFSDIR/var/cache/scratchpkg/packages && umount -l $ROOTFSDIR/var/cache/scratchpkg/packages
+	unmount $ROOTFSDIR/var/cache/scratchpkg/sources
+	unmount $ROOTFSDIR/var/cache/scratchpkg/packages
 }
 
 setup_base() {
-	# install pkgs
-	mountbind_cache
 	printstep "Updating ports..."
 	chroot_run scratch sync || die "Failed updating ports"
+	printstep "Strip down system to base..."
+	chroot_run pkgbase -y #|| die "Failed remove packages..."
 	printstep "Upgrading scratchpkg..."
 	chroot_run scratch upgrade -y --no-backup scratchpkg || die "Failed upgrade scratchpkg"
-	printstep "Upgrading scratchpkg-utils..."
-	chroot_run scratch upgrade -y --no-backup scratchpkg-utils || die "Failed upgrade scratchpkg-utils"
-	printstep "Strip down system to base..."
-	chroot_run pkgbase || die "Failed remove packages..."
+	#printstep "Upgrading scratchpkg-utils..."
+	#chroot_run scratch upgrade -y --no-backup scratchpkg-utils || die "Failed upgrade scratchpkg-utils"
 	printstep "Upgrading system..."
 	chroot_run scratch sysup -y --no-backup || die "Failed system upgrade"
 	[ "$ADD_PKGS" ] && {
 		printstep "Installing additional packages..."
-		chroot_run scratch install $ADD_PKGS -y || die "Failed installing additional packages"
+		chroot_run scratch install $(echo $ADD_PKGS | tr ',' ' ') -y || die "Failed installing additional packages"
 	}
 	printstep "Running pkgfix script..."
 	chroot_run pkgfix -r -y || die "Failed fixing packages"
@@ -102,14 +111,12 @@ setup_base() {
 		printstep "Fix broken packages (2nd time, for iso required packages)..."
 		chroot_run revdep -r -y || die "Failed fix broken packages..."
 	}
-	umountbind_cache
 
 	# remove initramfs, will created on installation
 	rm -f $ROOTFSDIR/boot/initrd-*
 }
 
 make_rootfs() {
-	# make rootfs
 	printstep "Creating rootfs: $VENOM_OUTPUT ..."
 	rm -f $OUTPUTDIR/$VENOM_OUTPUT $OUTPUTDIR/$VENOM_OUTPUT.md5
 	pushd $ROOTFSDIR >/dev/null
@@ -125,7 +132,6 @@ make_rootfs() {
 }
 
 make_iso() {
-	# prepare isolinux files
 	printstep "Preparing isolinux: $ISOLINUX_FILES ..."
 	mkdir -p $ISODIR/{venom,isolinux,boot}
 	for file in $ISOLINUX_FILES; do
@@ -173,11 +179,11 @@ make_iso() {
 	mount -o loop $ISODIR/boot/efiboot.img $ISODIR/boot/efiboot || die "Failed mount efiboot.img"
 	mkdir -p $ISODIR/boot/efiboot/EFI/boot
 	cp $ISODIR/boot/EFI/bootx64.efi $ISODIR/boot/efiboot/EFI/boot
-	umount -l $ISODIR/boot/efiboot
+	unmount $ISODIR/boot/efiboot
 	rm -fr $ISODIR/boot/efiboot
 
 	# save list packages to iso
-	for pkg in base $ADD_PKGS; do
+	for pkg in base $(echo $ADD_PKGS | tr ',' ' '); do
 		echo "$pkg" >> $ISODIR/venom/pkglist
 	done
 
@@ -221,44 +227,18 @@ Note:
 EOF
 }
 
-checkinput() {
-	if [ -z $1 ] || [[ $1 = -* ]]; then
-		printerror "This option need argument!"
-		exit 2
-	fi
-}
-
 parseopt() {
 	while [ "$1" ]; do
 		case $1 in
-			-iso)
-				MAKEISO=1;;
-			-keepworkdir)
-				keeworkdir=1;;
-			-pkgdir) checkinput $2
-				PKG_CACHE=$2
-				shift;;
-			-srcdir) checkinput $2
-				SRC_CACHE=$2
-				shift;;
-			-output) checkinput $2
-				VENOM_OUTPUT=$2
-				shift;;
-			-workdir) checkinput $2
-				WORKDIR=$2
-				shift;;
-			-pkg) checkinput $2
-				while [ "$2" ]; do
-					case $2 in
-						-*) break ;;
-						*) ADD_PKGS="$ADD_PKGS $2";;
-					esac
-					shift
-				done;;
-			-h|-help)
-				usage; exit 0;;
-			*)
-				VENOM=$1;;
+			-iso) MAKEISO=1;;
+			-keepwdir) keeworkdir=1;;
+			-pkgdir=*) PKG_CACHE=${1#*=};;
+			-srcdir=*) SRC_CACHE=${1#*=};;
+			-output=*) VENOM_OUTPUT=${1#*=};;
+			-workdir=*) WORKDIR=${1#*=};;
+			-pkg=*) ADD_PKGS=${1#*=};;
+			-h|-help) usage; exit 0;;
+			*) VENOM=$1;;
 		esac
 		shift
 	done
@@ -315,7 +295,7 @@ CWD=$PWD
 PKG_CACHE=${PKG_CACHE:-$CWD/cache_packages}
 SRC_CACHE=${SRC_CACHE:-$CWD/cache_sources}
 VENOM_OUTPUT=${VENOM_OUTPUT:-venom-$(date +"%Y%m%d")}
-VENOM_SOURCE=${VENOM:-venom-rootfs.txz}
+VENOM_SOURCE=${VENOM:-$CWD/venom-rootfs.txz}
 WORKDIR=${WORKDIR:-$CWD/workdir}
 OUTPUTDIR=${OUTPUTDIR:-$CWD/output}
 ROOTFSDIR=${ROOTFSDIR:-$WORKDIR/rootfs}
@@ -326,6 +306,6 @@ ISOLABEL=VENOMLIVE_$(date +"%Y%m%d")
 ISO_PKGS="dialog squashfs-tools grub-efi btrfs-progs reiserfsprogs xfsprogs"
 ISOLINUX_FILES="chain.c32 isolinux.bin ldlinux.c32 libutil.c32 reboot.c32 vesamenu.c32 libcom32.c32 poweroff.c32"
 
-main "$@"
+main
 
 exit 0
