updated

diff --git a/mkiso b/mkiso
--- a/mkiso
+++ b/mkiso
@@ -1,15 +1,20 @@
 #!/bin/bash -e
 
 interrupted() {
-	die
-	exit 2
+	die "Abort by user."
+}
+
+cleanup() {
+	[ "$cleanvenomsrc" = 1 ] && rm -fr $VENOMSRC
+	rm -fr $WDIR
 }
 
 die() {
 	[ "$@" ] && echo "ERROR: $@"
 	umount_pseudofs
 	umountbind_cache
-	rm -fr $WDIR
+	cleanup
+	exit 1
 }
 
 chroot_run() {
@@ -37,8 +42,8 @@ umount_pseudofs() {
 mountbind_cache() {
 	# mount bind cachedir
 	mkdir -p $SRC_CACHE $PKG_CACHE
-	mount --bind $SRC_CACHE $VENOMSRC/var/cache/scratchpkg/packages
-	mount --bind $PKG_CACHE $VENOMSRC/var/cache/scratchpkg/sources
+	mount --bind $SRC_CACHE $VENOMSRC/var/cache/scratchpkg/sources
+	mount --bind $PKG_CACHE $VENOMSRC/var/cache/scratchpkg/packages
 }
 
 umountbind_cache() {
@@ -50,7 +55,7 @@ umountbind_cache() {
 usage() {
 	cat << EOF
 Usage:
-  $(basename $0) [options]
+  $(basename $0) [options] <venom source>
   
 Options:
   -p <path>           set packages cache directory
@@ -60,6 +65,9 @@ Options:
   -k <kernel>         use custom kernel
   -o <name.iso>       output name for iso
   -h                  show this help msg
+  
+Note:
+  'venom source' should be a rootfs directory or rootfs tarball image
   
 EOF
 }
@@ -80,12 +88,13 @@ parseopt() {
 			-P) while [ "$2" ]; do
 					case $2 in
 						-*) break ;;
-						*) [ -z "$ADD_PKGS" ] && expkg="$2" || expkg="$ADD_PKGS $2"
+						*) [ -z "$ADD_PKGS" ] && ADD_PKGS="$2" || ADD_PKGS="$ADD_PKGS $2"
 					esac
 					shift
-				done ;;
+				done
+				shift ;;
 			-h) usage; exit 0;;
-			*)  VENOMSRC=$1
+			*)  VENOM=$1
 				shift;;
 		esac
 	done
@@ -96,25 +105,37 @@ WDIR=/tmp/venomiso
 ISOLINUXDIR=$CWD/isolinux
 DISTRONAME="Venom Linux"
 LABEL=VenomLive
-REQ_PKGS="dialog squashfs-tools libisoburn"
+REQ_PKGS="dialog squashfs-tools"
+VENOMSRC=/tmp/venomrootfs
 
 isolinux_files="chain.c32 isolinux.bin ldlinux.c32 libutil.c32 reboot.c32 vesamenu.c32
 isohdpfx.bin isolinux.cfg libcom32.c32 poweroff.c32 splash.png"
 
 parseopt $@
 
-OUTPUT=${OUTPUT:-venom.iso}
+OUTPUT=${OUTPUT:-venom-$(date +"%Y%m%d").iso}
 PKG_CACHE=${PKG_CACHE:-$CWD/cache_packages}
 SRC_CACHE=${SRC_CACHE:-$CWD/cache_sources}
 
 trap "interrupted" SIGHUP SIGINT SIGQUIT SIGTERM
 
-if [ -z $VENOMSRC ]; then
-	echo "Venom source dir not define! Aborted."
+if [ $UID != 0 ]; then
+	echo "ERROR: $(basename $0) need run as root."
+	exit 3
+fi
+
+if [ -z $VENOM ]; then
+	echo "Venom source not define! Aborted."
 	exit 1
-elif [ ! -d $VENOMSRC ]; then
-	echo "Directory '$VENOMSRC' not exist."
-	exit 1
+else
+	case $VENOM in
+		*.txz)	rm -fr $VENOMSRC
+				mkdir -p $VENOMSRC
+				cleanvenomsrc=1
+				echo "Extracting $VENOM..."
+				tar xf $VENOM -C $VENOMSRC;;
+		*)		VENOMSRC=$VENOM;;
+	esac
 fi
 
 rm -fr $WDIR
@@ -130,6 +151,8 @@ echo "$DISTRONAME" > $WDIR/isolinux/venomlive
 
 # install pkgs
 mountbind_cache
+chroot_run scratch sync
+chroot_run scratch sysup --no-confirm --no-backup
 chroot_run scratch install $REQ_PKGS $ADD_PKGS --no-confirm || die "failed install packages"
 umountbind_cache
 
@@ -154,8 +177,7 @@ xorriso -as mkisofs \
 		-l -cache-inodes \
 		-isohybrid-mbr $CWD/isolinux/isohdpfx.bin \
 		-partition_offset 16 \
-		-A "$LABEL" \
-		-V "$LABEL" \
+		-volid "$LABEL" \
 		-b isolinux/isolinux.bin \
 		-c isolinux/boot.cat \
 		-no-emul-boot \
@@ -163,5 +185,7 @@ xorriso -as mkisofs \
 		-boot-info-table \
 		-o $OUTPUT \
 		$WDIR || die "failed create iso"
+		
+cleanup
 
 exit 0
