add UEFI support

diff --git a/mkiso b/mkiso
--- a/mkiso
+++ b/mkiso
@@ -153,7 +153,7 @@ WDIR=/tmp/venomiso
 ISOLINUXDIR=$CWD/isolinux
 DISTRONAME="Venom Linux"
 LABEL=VenomLive
-REQ_PKGS="dialog squashfs-tools"
+REQ_PKGS="dialog squashfs-tools grub-efi"
 VENOMSRC=/tmp/venomrootfs
 ROOTFSURL="https://sourceforge.net/projects/venomlinux/files/venom-rootfs.txz"
 
@@ -167,6 +167,16 @@ fi
 
 if [ ! $(type -p mksquashfs ) ]; then
 	printerror "'squashfs-tools' not installed."
+	exit 1
+fi
+
+if [ ! $(type -p mkdosfs ) ]; then
+	printerror "'dosfstools' not installed."
+	exit 1
+fi
+
+if [ ! $(type -p isohybrid ) ]; then
+	printerror "'syslinux' not installed."
 	exit 1
 fi
 
@@ -263,22 +273,99 @@ mksquashfs $VENOMSRC $WDIR/filesystem/root.sfs \
 		-e $VENOMSRC/var/cache/scratchpkg/sources/* \
 		-e $VENOMSRC/var/cache/scratchpkg/packages/* \
 		-e $VENOMSRC/tmp/* || die "failed create squashed filesystem"
+		
+printstep "Setup UEFI mode..."
+GRUB_EFI_ARCH="x86_64"
+GRUB_EFI_IMG="bootx64.efi"
+mkdir -p $WDIR/boot/{grub/{fonts,${GRUB_EFI_ARCH}-efi},EFI}
+if [ -f /usr/share/grub/unicode.pf2 ];then
+	cp /usr/share/grub/unicode.pf2 $WDIR/boot/grub/fonts
+fi
+if [ -f $WDIR/isolinux/splash.png ]; then
+	cp $WDIR/isolinux/splash.png $WDIR/boot/grub/
+fi
+echo "set prefix=/boot/grub" > $WDIR/boot/grub-early.cfg
+cp -a /usr/lib/grub/${GRUB_EFI_ARCH}-efi/*.mod /usr/lib/grub/${GRUB_EFI_ARCH}-efi/*.lst $WDIR/boot/grub/${GRUB_EFI_ARCH}-efi || die "Failed copying efi files"
+cat  > $WDIR/boot/grub/grub.cfg << "EOF"
+set default=0
+set timeout=99
+
+# set debug=all
+# set pager=1
+
+insmod all_video
+if loadfont /boot/grub/fonts/unicode.pf2; then
+  set gfxmode=800x600
+  insmod efi_gop
+  insmod efi_uga
+  insmod video_bochs
+  insmod video_cirrus
+  insmod gfxterm
+  insmod png
+  terminal_output gfxterm
+fi
+
+if background_image /boot/grub/splash.png; then
+  set color_normal=light-gray/black
+  set color_highlight=white/black
+else
+  set color_normal=cyan/blue
+  set color_highlight=white/blue
+fi
+
+menuentry "Boot Venom Linux (UEFI mode)" {
+
+    linux /boot/vmlinuz ro quiet
+    initrd /boot/initrd
+}
+menuentry "Boot Venom Linux (UEFI mode) debug" {
+    set background_color=black
+    linux /boot/vmlinuz ro verbose
+    initrd /boot/initrd
+}
+EOF
+grub-mkimage-efi -c $WDIR/boot/grub-early.cfg -o $WDIR/boot/EFI/$GRUB_EFI_IMG -O ${GRUB_EFI_ARCH}-efi -p "" iso9660 normal search search_fs_file
+modprobe loop
+dd if=/dev/zero of=$WDIR/boot/efiboot.img count=4096
+mkdosfs -n VENOM-UEFI $WDIR/boot/efiboot.img || die "Failed mkdosfs"
+mkdir -p $WDIR/boot/efiboot
+mount -o loop $WDIR/boot/efiboot.img $WDIR/boot/efiboot || die "Failed mount efiboot.img"
+mkdir -p $WDIR/boot/efiboot/EFI/boot
+cp $WDIR/boot/EFI/$GRUB_EFI_IMG $WDIR/boot/efiboot/EFI/boot
+umount $WDIR/boot/efiboot
+rm -fr $WDIR/boot/efiboot
 
 printstep "Creating iso ($OUTPUT)..."
 rm -f $OUTPUT
-xorriso -as mkisofs \
-		-r -J -joliet-long \
-		-l -cache-inodes \
-		-isohybrid-mbr $CWD/isolinux/isohdpfx.bin \
-		-partition_offset 16 \
-		-volid "$LABEL" \
-		-b isolinux/isolinux.bin \
-		-c isolinux/boot.cat \
-		-no-emul-boot \
-		-boot-load-size 4 \
-		-boot-info-table \
-		-o $OUTPUT \
-		$WDIR || die "failed create iso"
+xorriso -as mkisofs -R -l -J \
+	-o $OUTPUT \
+	-A Venom \
+	-b isolinux/isolinux.bin \
+	-c isolinux/boot.cat \
+	-no-emul-boot \
+	-boot-load-size 4 \
+	-boot-info-table \
+	-eltorito-alt-boot \
+	-e boot/efiboot.img \
+	-no-emul-boot \
+	-input-charset utf-8 \
+	-V "$LABEL" $WDIR || die "failed create iso"
+	
+isohybrid -u $OUTPUT
+
+#xorriso -as mkisofs \
+		#-r -J -joliet-long \
+		#-l -cache-inodes \
+		#-isohybrid-mbr $CWD/isolinux/isohdpfx.bin \
+		#-partition_offset 16 \
+		#-volid "$LABEL" \
+		#-b isolinux/isolinux.bin \
+		#-c isolinux/boot.cat \
+		#-no-emul-boot \
+		#-boot-load-size 4 \
+		#-boot-info-table \
+		#-o $OUTPUT \
+		#$WDIR || die "failed create iso"
 		
 printstep "Generate md5sum..."
 md5sum $OUTPUT > $OUTPUT.md5
